#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Check if it's not a merge head
# So as to not run hook
if ! git rev-parse -q --no-revs --verify MERGE_HEAD
then
    exec < /dev/tty && node_modules/.bin/cz --hook || true
fi

exit 0